config/routes.rb
Rails.application.routes.draw do
  resources :skeletons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/skeleton.rb
class Skeleton < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skeletons_controller.rb
class SkeletonsController < ApplicationController
  before_action :set_skeleton, only: %i[ show edit update destroy ]

  # GET /skeletons or /skeletons.json
  def index
    @skeletons = Skeleton.all
  end

  # GET /skeletons/1 or /skeletons/1.json
  def show
  end

  # GET /skeletons/new
  def new
    @skeleton = Skeleton.new
  end

  # GET /skeletons/1/edit
  def edit
  end

  # POST /skeletons or /skeletons.json
  def create
    @skeleton = Skeleton.new(skeleton_params)

    respond_to do |format|
      if @skeleton.save
        format.html { redirect_to skeleton_url(@skeleton), notice: "Skeleton was successfully created." }
        format.json { render :show, status: :created, location: @skeleton }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skeleton.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skeletons/1 or /skeletons/1.json
  def update
    respond_to do |format|
      if @skeleton.update(skeleton_params)
        format.html { redirect_to skeleton_url(@skeleton), notice: "Skeleton was successfully updated." }
        format.json { render :show, status: :ok, location: @skeleton }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skeleton.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skeletons/1 or /skeletons/1.json
  def destroy
    @skeleton.destroy!

    respond_to do |format|
      format.html { redirect_to skeletons_url, notice: "Skeleton was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skeleton
      @skeleton = Skeleton.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skeleton_params
      params.require(:skeleton).permit(:name, :facts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skeletons_helper.rb
module SkeletonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rr7132</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skeletons/_form.html.erb
<%= form_with(model: skeleton) do |form| %>
  <% if skeleton.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(skeleton.errors.count, "error") %> prohibited this skeleton from being saved:</h2>

      <ul>
        <% skeleton.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :facts, style: "display: block" %>
    <%= form.text_area :facts %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/skeletons/_skeleton.html.erb
<div id="<%= dom_id skeleton %>">
  <p>
    <strong>Name:</strong>
    <%= skeleton.name %>
  </p>

  <p>
    <strong>Facts:</strong>
    <%= skeleton.facts %>
  </p>

</div>

app/views/skeletons/edit.html.erb
<h1>Editing skeleton</h1>

<%= render "form", skeleton: @skeleton %>

<br>

<div>
  <%= link_to "Show this skeleton", @skeleton %> |
  <%= link_to "Back to skeletons", skeletons_path %>
</div>

app/views/skeletons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Skeletons</h1>

<div id="skeletons">
  <% @skeletons.each do |skeleton| %>
    <%= render skeleton %>
    <p>
      <%= link_to "Show this skeleton", skeleton %>
    </p>
  <% end %>
</div>

<%= link_to "New skeleton", new_skeleton_path %>

app/views/skeletons/new.html.erb
<h1>New skeleton</h1>

<%= render "form", skeleton: @skeleton %>

<br>

<div>
  <%= link_to "Back to skeletons", skeletons_path %>
</div>

app/views/skeletons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @skeleton %>

<div>
  <%= link_to "Edit this skeleton", edit_skeleton_path(@skeleton) %> |
  <%= link_to "Back to skeletons", skeletons_path %>

  <%= button_to "Destroy this skeleton", @skeleton, method: :delete %>
</div>